namespace drl.sim.thread
{
	public enum MixerMode
	{
		MIXER_TRI = 1,
		MIXER_QUADP = 2,
		MIXER_QUADX = 3,
		MIXER_BICOPTER = 4,
		MIXER_GIMBAL = 5,
		MIXER_Y6 = 6,
		MIXER_HEX6 = 7,
		MIXER_FLYING_WING = 8,
		MIXER_Y4 = 9,
		MIXER_HEX6X = 10,
		MIXER_OCTOX8 = 11,
		MIXER_OCTOFLATP = 12,
		MIXER_OCTOFLATX = 13,
		MIXER_AIRPLANE = 14,
		MIXER_HELI_120_CCPM = 15,
		MIXER_HELI_90_DEG = 16,
		MIXER_VTAIL4 = 17,
		MIXER_HEX6H = 18,
		MIXER_PPM_TO_SERVO = 19,
		MIXER_DUALCOPTER = 20,
		MIXER_SINGLECOPTER = 21,
		MIXER_ATAIL4 = 22,
		MIXER_CUSTOM = 23,
		MIXER_CUSTOM_AIRPLANE = 24,
		MIXER_CUSTOM_TRI = 25,
		MIXER_QUADX_1234 = 26
	}
}
